Update properties.gd
Jummit/property-panel pull request #1
Opened 2023-05-16 17:18 UTC by scgm0

2023-05-16 17:28 UTC, Jummit reviewed
Thanks for the improvements!

2023-05-16 17:28 UTC, Jummit commented on addons/property_panel/properties.gd
> +	func _init(_name,_from=0,_to=100,_default = _from,_step = _from):
I don't think `_from` is a good default for `_step` here, 1 would make more sense.

2023-05-16 17:28 UTC, Jummit commented on addons/property_panel/properties.gd
> +	func _init(_name,_from=0.0,_to=1.0,_default = _from,_step = _from):
Here 0.1 would be a sensible default for `_step`.

2023-05-16 22:48 UTC, scgm0 commented on addons/property_panel/properties.gd
> +	func _init(_name,_from=0.0,_to=1.0,_default = _from,_step = _from):
godot编辑器或许是0？以此将step默认为设置可更改的最小值

2023-05-17 09:31 UTC, Jummit requested changes
Thanks for the changes! Just some small tweaks, then it's good to go.

2023-05-17 09:31 UTC, Jummit commented on addons/property_panel/path_picker_button/path_picker_button.gd
>  ## See [member FileDialog.filters].
This comment should be changed to something like "Members and their values set on new [FileDialog]s."

2023-05-17 09:31 UTC, Jummit commented on addons/property_panel/path_picker_button/path_picker_button.gd
> +var option : Dictionary
I think `options` makes more sense.

2023-05-17 15:53 UTC, scgm0 commented on addons/property_panel/path_picker_button/path_picker_button.gd
>  ## See [member FileDialog.filters].
My English is terrible, how about using "Members and their values set on new [FileDialog]s."?
(This is the reply after the machine flip)

2023-05-18 08:24 UTC, Jummit commented on addons/property_panel/path_picker_button/path_picker_button.gd
>  ## See [member FileDialog.filters].
Sounds great!

2023-05-18 08:27 UTC, merged

2023-05-18 08:27 UTC, Jummit commented
Thanks so much for the changes!